version: "3"
services:
  micro-orders:
    build: ./backend/services/orders
    environment:
      - PORT=8000
      - HOST=micro-orders
      - DEBUG=true
    volumes:
      - ./backend/services/orders:/service
    networks:
      - backend

  micro-products:
    build: ./backend/services/products
    environment:
      - PORT=8000
      - HOST=micro-products
      - DEBUG=true
    volumes:
      - ./backend/services/products:/service
    networks:
      - backend

  micro-shops:
    build: ./backend/services/shops
    environment:
      - PORT=8000
      - HOST=micro-shops
      - DEBUG=true
    volumes:
      - ./backend/services/shops:/service
    networks:
      - backend

  micro-transactions:
    build: ./backend/services/transactions
    environment:
      - PORT=8000
      - HOST=micro-transactions
      - DEBUG=true
    volumes:
      - ./backend/services/transactions:/service
    networks:
      - backend

  micro-users:
    build: ./backend/services/users
    environment:
      - PORT=8000
      - HOST=micro-users
      - DEBUG=true
    volumes:
      - ./backend/services/users:/service
    networks:
      - backend

  micro-restaurants:
    build: ./backend/services/restaurants
    environment:
      - PORT=8000
      - HOST=micro-restaurants
      - DEBUG=true
    volumes:
      - ./backend/services/restaurants:/service
    networks:
      - backend

  frontend-web:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile.dev
    environment:
      - PORT=3000
      - HOST=frontend-web
    volumes:
      - ./frontend/web:/app
      - /app/node_modules
    networks:
      - frontend

  gateway:
    build: ./gateway
    ports:
      - "80:80"
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
