version: "3"
services:
  micro-orders:
    build: ./backend/services/orders
    environment:
      - PORT=8000
      - HOST=micro-orders
    networks:
      - backend

  micro-products:
    build: ./backend/services/products
    environment:
      - PORT=8000
      - HOST=micro-products
    networks:
      - backend

  micro-shops:
    build: ./backend/services/shops
    environment:
      - PORT=8000
      - HOST=micro-shops
    networks:
      - backend

  micro-transactions:
    build: ./backend/services/transactions
    environment:
      - PORT=8000
      - HOST=micro-transactions
    networks:
      - backend

  micro-users:
    build: ./backend/services/users
    environment:
      - PORT=8000
      - HOST=micro-users
    networks:
      - backend

  micro-restaurants:
    build: ./backend/services/restaurants
    environment:
      - PORT=8000
      - HOST=micro-restaurants
    networks:
      - backend

  frontend-web:
    build: ./frontend/web
    environment:
      - PORT=3000
      - HOST=frontend-web
    networks:
      - frontend

  gateway:
    build: ./gateway
    ports:
      - "80:80"
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
