version: "3"
services:
    micro-orders:
        build: ./backend/services/orders
        ports:
            - "6501:6501"
        environment:
            - PORT=6501
            - HOST=micro-orders
        networks:
            - backend

    micro-products:
        build: ./backend/services/products
        ports:
            - "6502:6502"
        environment:
            - PORT=6502
            - HOST=micro-products
        networks:
            - backend

    micro-shops:
        build: ./backend/services/shops
        ports:
            - "6503:6503"
        environment:
            - PORT=6503
            - HOST=micro-shops
        networks:
            - backend

    micro-transactions:
        build: ./backend/services/transactions
        ports:
            - "6504:6504"
        environment:
            - PORT=6504
            - HOST=micro-transactions
        networks:
            - backend

    micro-users:
        build: ./backend/services/users
        ports:
            - "6505:6505"
        environment:
            - PORT=6505
            - HOST=micro-users
        networks:
            - backend

    frontend-web:
        build: ./frontend/web
        ports:
            - "3000:3000"
        environment:
            - PORT=3000
            - HOST=frontend-web
        networks:
            - frontend

    gateway:
        build: ./gateway
        ports:
            - "80:80"
        networks:
            - frontend
            - backend

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
